version: '3.8'

services:
  web:
    image: warlicks/flashcard-hub
    env_file:
      - .env
    expose:
      - "5000" # This is the exposure for ports within the docker network. 

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80" # This is the exposure for ports outside the docker network.
    depends_on:
      - web

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    expose:
      - "5432" # This is the exposure for ports within the docker network.
    ports:
      - "8080:5432"

volumes:
  pg-data:
    driver: local
