version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "5000" # This is the exposure for ports within the docker network. 

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80" # This is the exposure for ports outside the docker network.
    depends_on:
      - web
