version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./app:/app
    #   - ./instance:/instance
    env_file:
      - .env
    ports:
      - 5000:5000
    expose:
      - "5000"
    # networks:
    #   my-network:
    #     aliases:
    #       - web
    #   nginx:
    #     image: nginx:latest
    #     volumes:
    #       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #     ports:
    #       - "80:80"
    #     depends_on:
    #       - web
